--- 
apiVersion: v1
kind: Service
metadata: 
  name: hello-service
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector: 
    app: hello-service